- name: Learning Conditions
  hosts: all
  become: yes
  tasks:
  - name: Install {{ item }} package Centos OS
    yum: 
      name: "{{ item }}"
      state: present
    with_items:
      - httpd
      - mysql-server
      - php
      - php-mysql

  
  - name: Start and Enable {{ item }} service in Centos
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
